---
simulation:
  scale_ratio: 3600
  credential:
    username: chi-sim
    password: chi-sim
  enable_osg: yes
  enable_ml: no
  enable_monitor: yes

framework:
  global_mgr:
    clean_run: yes
  rsrc_mgr:
    host: 127.0.0.1
  frontend:
    request_forecaster:
      window: 168
      steps: 3
      retrain:
        enabled: yes
        length: 30000
  databus:
    rabbitmq: 127.0.0.1
  database:
    influxdb: 127.0.0.1
    mongodb: 127.0.0.1

workloads:
  machine_events:
    payload: ../datasets/machine_events/compute_haswell.csv
    timestamp_col: 0
  osg_jobs:
    payload: ../datasets/osg_jobs/osg_jobs.csv
    timestamp_col: 13
  chameleon_requests:
    payload: datasets/user_requests/lease_info.csv
    timestamp_col: -1
